e_commerce_pbp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from .views import show_home, menu_list_json, menu_list_xml, menu_detail_json, menu_detail_xml, add_menu_item, delete_item
from .views import register, login_user, logout_user, edit_menu, delete_item, add_menu_item_ajax, create_menu_flutter
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('', show_home, name='show_home'),
    path('api/menu/json/', menu_list_json, name='menu_list_json'),
    path('api/menu/xml/', menu_list_xml, name='menu_list_xml'),
    path('api/menu/json/<int:pk>/', menu_detail_json, name='menu_detail_json'),
    path('api/menu/xml/<int:pk>/', menu_detail_xml, name='menu_detail_xml'),
    path('add-menu/', add_menu_item, name='add_menu_item'),
    path('delete/<int:pk>/', delete_item, name='delete_item'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-menu/<int:pk>', edit_menu, name='edit_menu'),
    path('add-menu-ajax/', add_menu_item_ajax, name='add_menu_item_ajax'),
    path('create-flutter/', create_menu_flutter, name='create_mood_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField()
    quantity = models.IntegerField()
    image = models.CharField(max_length=255)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import Item

class MenuForm(forms.ModelForm):
    class Meta:
        model = Item 
        fields = ['name', 'price', 'description', 'image', 'quantity']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.TextInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'})
        }

main/views.py
import datetime
from itertools import chain
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .models import Item
from .forms import MenuForm
import json

@login_required(login_url='/login')
def show_home(request):
    default_items = [
        {
            'user': {
                'username': 'Valen (default)'
            },
            'name': 'Es Kulkul Uni Bakwan', 
            'price': 70, 
            'description': 'Es Kulkul Uni Bakwan, es asli dari Uni Bakwan Onde Mande',
            'quantity': 10,
            'image': 'https://i.pinimg.com/736x/42/b1/22/42b12243ca70053a7c6f22241787f271.jpg'
        },
        {
            'user': {
                'username': 'Valen (default)'
            },
            'name': 'Ayam Goreng Bunda Mewing', 
            'price': 25, 
            'description': 'Merupakan salah satu ayam goreng langka yang dibuat oleh bunda yang mewing.',
            'quantity': 73,
            'image': 'https://steamuserimages-a.akamaihd.net/ugc/2270441744978599352/3A97A06E3670819C1E5A4525DED7FBF4DAC5DE21/?imw=512&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false'
        },
        {
            'user': {
                'username': 'Valen (default)'
            },
            'name': 'Mie Keriting', 
            'price': 16, 
            'description': 'Mie keriting! AWAS bisa membuatmu giting...',
            'quantity': 100,
            'image': 'https://i.ytimg.com/vi/-7uwIsEe1jY/maxresdefault.jpg'
        }
    ]

    # Fetching items from the database
    db_items = Item.objects.all()

    # Combining default items with database items
    all_items = list(chain(default_items, db_items))

    # my_entry = Item.objects.filter(user=request.user)

    context = {
        'nama': 'Valentino Kim Fernando',
        'kelas': 'PBP F',
        'items': all_items,
        # 'my_items': my_entry,
        'logo' : 'https://i.imgur.com/qm2xL9P.png',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'home.html', context)

def add_menu_item(request):
    form = MenuForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item_entry = form.save(commit=False)
        item_entry.user = request.user
        item_entry.save()
        return redirect('/')
    
    return render(request, 'add_menu.html', {'form': form})

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('home:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("home:show_home"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
      
      else:
            messages.error(request, 'Username atau password kamu salah!')

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('home:login'))
    response.delete_cookie('last_login')
    return response

def menu_list_json(request):
    # data = serializers.serialize('json', Item.objects.all())
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def menu_list_xml(request):
    # data = serializers.serialize('xml', Item.objects.all())
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def menu_detail_json(request, pk):
    data = serializers.serialize('json', [Item.objects.get(pk=pk)])
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def menu_detail_xml(request, pk):
    data = serializers.serialize('xml', [Item.objects.get(pk=pk)])
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def edit_menu(request, pk):
    # Get mood entry berdasarkan id
    menu = Item.objects.get(pk=pk)

    # Set mood entry sebagai instance dari form
    form = MenuForm(request.POST or None, instance=menu)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('home:show_home'))

    context = {'form': form}
    return render(request, "edit_menu.html", context)

def delete_item(request, pk):
    item = Item.objects.get(pk=pk)
    item.delete()
    return HttpResponseRedirect(reverse('home:show_home'))

@csrf_exempt
@require_POST
def add_menu_item_ajax(request):
    name = request.POST.get("name")
    price = request.POST.get("price")
    description = request.POST.get("description")
    image = request.POST.get("image")
    user = request.user
    username = user

    new_food = Item(name=name, price=price,
                    description=description, image=image, 
                    user=user, username=username)
    new_food.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_menu_flutter(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
                        
            new_product = Item.objects.create(
                user=request.user,
                name=data['nama'], 
                price=int(data['harga']),
                description=data['deskripsi'],
            )
            
            return JsonResponse({
                "status": "success",
                "message": "Product berhasil ditambahkan!"
            }, status=200)
            
        except Exception as e:
            return JsonResponse({
                "status": "error",
                "message": str(e)
            }, status=400)
            
    return JsonResponse({
        "status": "error",
        "message": "Invalid request method"
    }, status=401)

main/templates/add_menu.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Buat Menu</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center" style="background-image: url('/static/bg.svg'); background-size: cover;">
  <div class="p-8 bg-white rounded-lg shadow-lg max-w-sm w-full form-style my-20">
    <img src="{% static 'Warmindawg_logo.png' %}" alt="Warmindawg Logo">
    <h1 class="text-xl font-bold mb-4 mt-4 text-center">
      <span class="text-2xl font-extrabold text-red-500">Edit Menu</span>
    </h1>
    <form method="POST" action="" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid grid-cols-2 gap-4">
        {% for field in form %}
        <div class="flex flex-col gap-2 {% if field.name == 'description' %}col-span-2{% endif %}">
          <label for="{{ field.id_for_label }}" class="font-bold">
            {{ field.label }}
          </label>
          <div>{{ field }}</div>
          {% if field.errors %}
          <ul class="list-disc bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mt-2">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
          {% if field.help_text %}
          <p class="text-xs text-gray-600">{{ field.help_text }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      <div class="add-menu text-center pt-5">
        <button type="submit" class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600 focus:outline-none focus:shadow-outline">
          <strong>Simpan Menu</strong>
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

main/templates/edit_menu.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ubah Menu</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center" style="background-image: url('/static/bg.svg'); background-size: cover;">
  <div class="p-8 bg-white rounded-lg shadow-lg max-w-sm w-full form-style my-20">
    <img src="{% static 'Warmindawg_logo.png' %}" alt="Warmindawg Logo">
    <h1 class="text-xl font-bold mb-4 mt-4 text-center">
      <span class="text-2xl font-extrabold text-red-500">Edit Menu</span>
    </h1>
    <form method="POST" action="" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid grid-cols-2 gap-4">
        {% for field in form %}
        <div class="flex flex-col gap-2 {% if field.name == 'description' %}col-span-2{% endif %}">
          <label for="{{ field.id_for_label }}" class="font-bold">
            {{ field.label }}
          </label>
          <div>{{ field }}</div>
          {% if field.errors %}
          <ul class="list-disc bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mt-2">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
          {% if field.help_text %}
          <p class="text-xs text-gray-600">{{ field.help_text }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      <div class="add-menu text-center pt-5">
        <button type="submit" class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600 focus:outline-none focus:shadow-outline">
          <strong>Simpan Menu</strong>
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'navbar.html' %}
<head>
    <title>Warmindawg</title>
</head>
<body>
    <div class="add-menu" style="justify-content: center; text-align: center; display: flex; gap: 20px; margin-bottom: 20px">
        <a href="{% url 'home:logout' %}" >
            <button class="w-full px-4 py-2 text-white bg-red-500 hover:bg-red-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
                <strong>Logout</strong>
            </button>
        </a>
        <a href="{% url 'home:add_menu_item' %}">
            <button class="w-full px-4 py-2 text-white bg-orange-500 hover:bg-orange-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-600 focus:ring-opacity-50">
                <strong>Tambahkan Menu</strong>
            </button>
        </a>
        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
          Tambahkan Menu By AJAX
        </button>
    </div>
    <p style="text-align: center;">
        🔥🧑🏻‍🍳 Pemasak Warmindawg hari ini: <br /> 
        <strong>
            {{ nama }} dari {{ kelas }}
        </strong>
    </p>
    {% if not items %}
        <h3 class="text-center pt-8 text-xl text-red-500">Tidak ada menu yang tersedia</h3>
    {% else %}
    <h3 class="text-center pt-8 text-xl text-red-500">
        <strong>Menu:</strong>
    </h3>
    <ul>
        {% for item in items %}
        <li>
            <img src="{{ item.image }}" alt="{{ item.name }}" class="fixed-image">
            <p class="pt-4">
            <strong>{{ item.name }}</strong>
            </p>
            <p class="text-red-500 font-bold">
                Rp{{ item.price }}.000
            </p>
            <p class="product-description pt-4">
                {{ item.description }}
            </p>
            <p class="product-description pt-4">
                <strong>Added by:</strong> {{ item.user.username }}
            </p>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <h3 class="text-center pt-8 text-xl text-red-500">
        <strong>Menuku:</strong>
    </h3>
    <!-- {% if not my_items %}
        <h3 class="text-center pt-4">
            <strong>Kamu belum memasukkan menu!</strong>
        </h3>
    {% else %}
    <ul>
        {% for item in my_items %}
        <li>
            <img src="{{ item.image }}" alt="{{ item.name }}" class="fixed-image">
            <p class="pt-4">
            <strong>{{ item.name }}</strong>
            </p>
            <p class="text-red-500 font-bold">
                Rp{{ item.price }}.000
            </p>
            <p class="product-description pt-4">
                {{ item.description }}
            </p>
            <p class="product-description pt-4">
                <strong>Added by:</strong> {{ item.user.username }}
            </p>
                <div style="justify-content: center; text-align: center; display: flex; gap: 12px; margin-bottom: 20px" class="pt-4">
                    <a href="{% url 'home:edit_menu' item.pk %}">
                        <button  class="w-full px-10 py-2 text-white bg-orange-500 hover:bg-orange-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-600 focus:ring-opacity-50">
                            <strong>Ubah</strong>
                        </button>
                    </a>
                    <a href="{% url 'home:delete_item' item.pk %}">
                        <button class="w-full px-10 py-2 text-white bg-red-500 hover:bg-red-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
                            <strong>Hapus</strong>
                        </button>
                    </a>
                </div>
        </li>
        {% endfor %}
    </ul>
    {% endif %} -->

    <div id="item_entry_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
        <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 border-b rounded-t">
            <h3 class="text-xl font-semibold text-gray-900">
              Add New Mood Entry
            </h3>
            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
              <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <div class="px-6 py-4 space-y-6 form-style">
            <form id="itemEntryForm">
                <div class="mb-4">
                    <label for="name" class="block text-sm font-medium text-gray-700">Nama</label>
                    <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-red-700" placeholder="Masukkan nama produk" required>
                  </div>
                
                  <!-- Price Field -->
                  <div class="mb-4">
                    <label for="price" class="block text-sm font-medium text-gray-700">Harga (Rp[HARGAMU].000)</label>
                    <input type="number" id="price" name="price" min="1" max="100000" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-red-700" placeholder="Masukkan harga produk" required>
                  </div>
                
                  <!-- Description Field -->
                  <div class="mb-4">
                    <label for="description" class="block text-sm font-medium text-gray-700">Deskripsi</label>
                    <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-red-700" placeholder="Masukkan deskripsi produk" required></textarea>
                  </div>
                
                  <!-- Image Field -->
                  <div class="mb-4">
                    <label for="image" class="block text-sm font-medium text-gray-700">Image (URL)</label>
                    <input type="text" id="image" name="image" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-red-700" placeholder="Masukkan URL gambar" required>
                  </div>
            </form>
          </div>
          <!-- Modal footer -->
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
            <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
            <button type="submit" id="submitItemEntry" form="itemEntryForm" class="bg-red-700 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
          </div>
        </div>
      </div>

    <div class="text-center pt-20">
        <h5>Username: {{ user.username }}</h5>
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
</body>
<script>
    async function getItemEntries(){
        return fetch("{% url 'home:menu_list_json' %}").then((res) => res.json())
    }

    async function refreshItemEntries(){
        document.getElementById("item_entry_cards").innerHTML = "";
        document.getElementById("item_entry_cards").className = "";
        const itemEntries = await getItemEntries();
        let htmlString = "";
        let classNameString = "";

        if (itemEntries.length === 0 ) {
            classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
            htmlString = `
                <h3 class="text-center pt-4">
                    <strong>Kamu belum memasukkan menu!</strong>
                </h3>
            `;
        }
        else {
            classNameString = "flex flex-wrap justify-center list-none";
            itemEntries.forEach((item) => {
                htmlString += `
                <li>
                    <img src="${item.fields.image}" alt="${item.fields.name}" class="fixed-image">
                    <p class="pt-4">
                        <strong>${item.fields.name}</strong>
                    </p>
                    <p class="text-red-500 font-bold">
                        Rp${item.fields.price}.000
                    </p>
                    <p class="product-description pt-4">
                        ${item.fields.description}
                    </p>
                    <p class="text-red-500 font-bold">
                        Stock: ${item.fields.quantity}
                    </p>
                    <p class="product-description pt-4">
                        <strong>Added by:</strong> ${item.fields.username}
                    </p>
                    <div style="justify-content: center; text-align: center; display: flex; gap: 12px; margin-bottom: 20px" class="pt-4">
                        <a href="/edit-menu/${item.pk}">
                            <button class="w-full px-10 py-2 text-white bg-orange-500 hover:bg-orange-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-600 focus:ring-opacity-50">
                                <strong>Ubah</strong>
                            </button>
                        </a>
                        <a href="/delete/${item.pk}">
                            <button class="w-full px-10 py-2 text-white bg-red-500 hover:bg-red-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
                                <strong>Hapus</strong>
                            </button>
                        </a>
                    </div>
                </li>
            `;
        })}
        document.getElementById("item_entry_cards").className = classNameString;
        document.getElementById("item_entry_cards").innerHTML = htmlString;
    }
    refreshItemEntries();

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);

    function addItemEntry() {
        fetch("{% url 'home:add_menu_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#itemEntryForm')),
        })
        .then(response => refreshItemEntries())

        document.getElementById("itemEntryForm").reset(); 
        document.querySelector("[data-modal-toggle='crudModal']").click();

        return false;
    }
    
    document.getElementById("itemEntryForm").addEventListener("submit", (e) => {
            e.preventDefault();
            addItemEntry();
        })
</script>
{% endblock content %} 

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center" style="background-image: url('/static/bg.svg');  background-size: cover;">
  <div class="p-8 bg-white rounded-lg shadow-lg max-w-sm w-full form-style">
    <img src="../static/Warmindawg_logo.png">
    <h1 class="text-xl font-bold mb-4 mt-4 text-center">
      <span class="text-2xl font-extrabold text-red-500">Oy!</span> yuk login dulu
    </h1>
    <form method="POST" action="">
      {% csrf_token %}
      <div class="space-y-4">
        {% for field in form %}
        <div>
          {{ field.label_tag }}
          {{ field }}
          {% if field.help_text %}
          <p class="text-xs text-gray-600">{{ field.help_text }}</p>
          {% endif %}
          {% for error in field.errors %}
          <p class="text-red-500 text-xs mt-1">{{ error }}</p>
          {% endfor %}
        </div>
        {% endfor %}
        <div>
          <button type="submit" class="w-full px-4 py-2 text-white bg-red-500 hover:bg-red-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
            <strong>Masuk</strong>
          </button>
        </div>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      <ul>
        {% for message in messages %}
        <li class="text-sm text-red-600">{{ message }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    <p class="mt-4 text-sm text-center">
      Belum pernah nge-Warmindawg? <br />
      <a href="{% url 'home:register' %}" class="text-red-500 hover:text-red-600 hover:font-semibold">Kenalan yuk</a>
    </p>
  </div>
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}

<div class="min-h-screen flex items-center justify-center" style="background-image: url('/static/bg.svg'); background-size: cover;">
  <div class="p-8 bg-white rounded-lg shadow-lg max-w-sm w-full form-style my-20">
    <img src="{% static 'Warmindawg_logo.png' %}" alt="Warmindawg Logo">
    <h1 class="text-xl font-bold mb-4 mt-4 text-center">
      <span class="text-2xl font-extrabold text-red-500">Kenalan yuk!</span>
    </h1>
  <form method="POST">
    {% csrf_token %}
    <div class="space-y-4">
      {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <p class="text-xs text-gray-600">{{ field.help_text }}</p>
        {% endif %}
      </div>
      {% endfor %}
      <div>
        <button type="submit" class="w-full px-4 py-2 text-white bg-red-500 hover:bg-red-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
          <strong>Daftar</strong>
        </button>
      </div>
    </div>
  </form>

  <p class="mt-4 text-sm text-center">
    Sudah punya akun? <br />
    <a href="{% url 'home:login' %}" class="text-red-500 hover:text-red-600 hover:font-semibold">Login di sini</a>
  </p>
{% endblock content %}